### ISSUE TITLE
failed to load modules

### ISSUE THREAD

**Issue by iCaran** [sergeyklay/gohugo-theme-ed#139] opened 2024-08-01 20:42 UTC
Just installed this theme, copied the config as is from exampleSite to main directory, basically did exactly wha the Installation section on Documentation says, but on "hugo mod get", i get:

`$ hugo mod get

go: github.com/sergeyklay/gohugo-theme-ed imports
	fmt: package fmt is not in std (/snap/hugo/20249/src/fmt)
go: github.com/sergeyklay/gohugo-theme-ed imports
	log: package log is not in std (/snap/hugo/20249/src/log)
go: github.com/sergeyklay/gohugo-theme-ed imports
	os: package os is not in std (/snap/hugo/20249/src/os)
go: github.com/sergeyklay/gohugo-theme-ed imports
	regexp: package regexp is not in std (/snap/hugo/20249/src/regexp)
go: github.com/sergeyklay/gohugo-theme-ed imports
	strings: package strings is not in std (/snap/hugo/20249/src/strings)
hugo: collected modules in 980 ms
Error: failed to load modules: failed to get ["-d" "github.com/sergeyklay/gohugo-theme-ed@upgrade"]: failed to execute 'go [get -d github.com/sergeyklay/gohugo-theme-ed@upgrade]': failed to execute binary "go" with args [get -d github.com/sergeyklay/gohugo-theme-ed@upgrade]: go: github.com/sergeyklay/gohugo-theme-ed imports
	fmt: package fmt is not in std (/snap/hugo/20249/src/fmt)
go: github.com/sergeyklay/gohugo-theme-ed imports
	log: package log is not in std (/snap/hugo/20249/src/log)
go: github.com/sergeyklay/gohugo-theme-ed imports
	os: package os is not in std (/snap/hugo/20249/src/os)
go: github.com/sergeyklay/gohugo-theme-ed imports
	regexp: package regexp is not in std (/snap/hugo/20249/src/regexp)
go: github.com/sergeyklay/gohugo-theme-ed imports
	strings: package strings is not in std (/snap/hugo/20249/src/strings)
 *errors.errorString
`

**Comment by sergeyklay** [comment] 2024-08-18 20:19
Hi @iCaran, 

Apologies for the delayed response.

It seems like the issue might be related to an incorrect installation of Hugo, which is causing the necessary dependencies for module management to be missing. For example this kind of problem can sometimes occur if Hugo was installed via Snap. I would recommend trying to reinstall Hugo using a different method, such as Homebrew (if you’re on macOS) or apt (for Ubuntu).

I hope this helps. If you have any more questions, feel free to ask!

**Comment by elliottw** [comment] 2024-09-01 21:13
I am having the same issue installing Hugo with Homebrew on macOS.

**Comment by sergeyklay** [comment] 2024-09-02 13:08
I'll try to sort out in detail ASAP. Thank you for the report.

**Comment by sergeyklay** [comment] 2024-09-13 16:16
Hi @iCaran @elliottw,

First of all, I apologize for the delayed response and sincerely hope that this hasn't caused any issues or delays in your projects.

Could you please let me know how you installed Go? This information will help in understanding if the problem might be related to the installation method.

From the initial error message by @iCaran, it looks like standard Go packages are being installed, which is unusual for typical Hugo usage. This behavior might indicate that the Go environment on your machine isn't set up correctly or that Hugo is trying to fetch modules from a clean state. This could be due to missing libraries in your current environment or issues with module settings in `go.mod`. I couldn’t replicate the problem on various environments, so I need more details to investigate further.

Could you please provide the following diagnostic information?

**Go Version:**
```bash
go version
```

**Go Environment Variables:**
```
go env
```

**Check GOPATH and GOROOT:**
```bash
echo $GOPATH
echo $GOROOT
```

**Hugo Version:**
```bash
hugo version
```

**go.mod**
```bash
cat <path-to-your-project>/go.mod
```

Additionally, if you have repositories with your project code, sharing the links would be helpful. Alternatively, you can send them to me as an archive at `contact at serghei do pl`

Ideally, create a minimal reproduction of the issue on a fresh template rather than linking to your site's repository: https://hugoblox.com/hugo-themes/

This will help me better understand the configuration of your environment and pinpoint the issue.  I thank you in advance, hope for your understanding, and once again apologize for the delayed response.

**Comment by elliottw** [comment] 2024-09-14 15:18
Thanks for looking into this for us. On my end, it was all user error. I did not follow your instructions https://gohugo-theme-ed.netlify.app/documentation/ and instead I just git cloned the theme repo and I'm assuming that caused some issue. I ended up starting over, creating a new repo with your instructions and it worked without issue.

**Comment by sergeyklay** [comment] 2024-09-26 10:43
I suggest closing this issue, and if any problems come up, please don't hesitate to let me know. We can always reopen this issue or create a new one.

**Closed by sergeyklay** 2024-09-26 10:43 UTC
Labels: good first issue
